---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 27220.
--- DateTime: 2023/10/25 19:42
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del',KEYS[1])
end
return 0


